import re

def humanize_1st(text):
    t = text
    
    # 1. Staged framing & AI boilerplate transitions
    t = t.replace('Rather than relying on hazardous acetonitrile, the mobile phase uses bio-ethanol and water (5:95, v/v).',
                  'Acetonitrile was replaced with an eco-conscious eluent combining bio-ethanol and water (5:95, v/v).')
    t = t.replace('To omit toxic acetonitrile, our chromatographic system runs on bio-ethanol and water (5:95, v/v).',
                  'Acetonitrile was replaced with an eco-conscious eluent combining bio-ethanol and water (5:95, v/v).')
    t = t.replace('To eliminate hazardous acetonitrile, our mobile phase pairs bio-ethanol and water (5:95, v/v).',
                  'Acetonitrile was eliminated, utilizing an eluent combining bio-ethanol and water (5:95, v/v).')
    t = t.replace('Here, we present the development and validation of an isocratic ethanol-based RP-HPLC method',
                  'This work establishes an isocratic bio-ethanol RP-HPLC protocol')
    t = t.replace('We established and qualified an isocratic bio-ethanol RP-HPLC protocol for quantifying both actives in retail dispensers, contrasting its footprint against five sustainability frameworks.',
                  'This investigation validates an isocratic bio-ethanol RP-HPLC protocol for quantifying both active pyrethroids in retail dispensers, contrasting its footprint against five sustainability frameworks.')
    t = t.replace('sharply improved peak symmetry and pulled both compounds into a practical 22-min window.',
                  'improved chromatographic symmetry while resolving both targets inside 22 min.')
    t = t.replace('enhanced chromatographic symmetry, resolving both targets inside 22 min.',
                  'improved chromatographic symmetry while resolving both targets inside 22 min.')
    
    # Clean section numbers or bullet points
    t = re.sub(r'^\d+\.\s+', '', t, flags=re.MULTILINE)
    t = re.sub(r'^\d+\.\d+\.\s+', '', t, flags=re.MULTILINE)
    t = re.sub(r'^[•\-\*]\s+', '', t, flags=re.MULTILINE)
    
    # Rephrase pseudo-lists in Multi-Metric section (GEARS: ..., AGSA: ...) to flowing scientific paragraphs
    t = t.replace('GEARS: Bio-ethanol scored 78.75% compared to 28.75% for acetonitrile. The total mobile phase scored 79.81%, compared to 43.00% for the legacy HPLC eluent and 32.5%–38.0% for GC-MS and HPTLC protocols reliant on dichloromethane, hexane, or toluene (Table 8, Figure 8C).',
                  'Regarding solvent greenness via GEARS, bio-ethanol scored 78.75% versus 28.75% for acetonitrile. The overall binary mobile phase registered 79.81%, whereas conventional HPLC eluent attained 43.00% and literature GC-MS/HPTLC protocols reliant on dichloromethane, hexane, or toluene scored 32.5%–38.0% (Table 8, Figure 8C).')
    t = t.replace('AGSA: The 12-principle star area almost doubled, jumping from 18.65% (0.559/3.000) to 36.31% (1.089/3.000) through the switch to a renewable modifier, reduced toxicity, and safer handling (Figure 5C, Figure 7C). Literature GC-MS (15.2%) and HPTLC (22.4%) scored far lower.',
                  'In AGSA polygonal evaluation, the 12-principle star area reached 36.31% (1.089/3.000) compared to 18.65% (0.559/3.000) for traditional HPLC, driven by renewable solvent sourcing, reduced toxicity, and safer laboratory handling (Figure 5C, Figure 7C); literature GC-MS (15.2%) and HPTLC (22.4%) exhibited substantially smaller areas.')
    t = t.replace('AGSA-Prep: Direct canister depressurization followed by solvent dilution achieved an AGSA-Prep area of 53.22% (1.505/2.828), vs 31.12% for conventional testing and 24.5%–38.0% for published extraction procedures (Figure 8A, B).',
                  'For sample preparation greenness, direct canister depressurization followed by dilution attained an AGSA-Prep coverage of 53.22% (1.505/2.828), outperforming conventional testing (31.12%) and literature extraction workflows (24.5%–38.0%) (Figure 8A, B).')
    t = t.replace('MoGAPI and ComplexMoGAPI: Overall scores rose from 33.33 to 60.00 on MoGAPI and from 35.83 to 63.00 on ComplexMoGAPI, outperforming published pyrethroid assays (28.5–40.5) (Figure 7A, B).',
                  'Assessment with MoGAPI and ComplexMoGAPI yielded overall scores of 60.00 and 63.00, respectively, markedly exceeding legacy HPLC (33.33 and 35.83) and published pyrethroid assays (28.5–40.5) (Figure 7A, B).')
    t = t.replace('General Metrics: The AGREE score advanced from 0.47 to 0.77 (Figure 7D), the Analytical Eco-Scale score rose from 72 to 88 (a 57% reduction in penalty points), and WAC whiteness climbed from 71.2% to 86.0% (Table 6, Figure 4).',
                  'Consensus across general metrics demonstrated substantial gains: the AGREE score reached 0.77 versus 0.47 (Figure 7D), the Analytical Eco-Scale score attained 88 versus 72 (a 57% decrease in penalty points), and total WAC whiteness reached 86.0% compared to 71.2% (Table 6, Figure 4).')

    # Concise scientific tightening to elevate TTR
    replacements = [
        ('Pressurized domestic insect sprays routinely pair a fast-acting knockdown pyrethroid with a persistent killing agent.',
         'Pressurized household insecticides frequently pair fast-acting knockdown pyrethroids with persistent lethal actives.'),
        ('In KIROX MD aerosols, D-tetramethrin (type I) delivers the initial knockdown, while trans-cyphenothrin (type II) ensures mortality [1–5].',
         'In commercial KIROX MD aerosols, D-tetramethrin (type I) provides rapid knockdown, while trans-cyphenothrin (type II) secures mortality [1–5].'),
        ('Analyzing these active ingredients in finished aerosol products is practically challenging.',
         'Assaying both actives within commercial dispensers poses analytical challenges.'),
        ('The active pyrethroids make up only 0.1% to 3.0% w/v of the formulation, dispersed within heavy petroleum distillates and liquefied hydrocarbon propellants like propane and butane [6].',
         'Active ingredients comprise merely 0.1%–3.0% w/v, dispersed within heavy petroleum distillates and liquefied hydrocarbon propellants [6].'),
        ('Both compounds are lipophilic (log P > 4.5) and share overlapping UV absorption bands between 220 and 230 nm.',
         'Both pyrethroids exhibit hydrophobic properties (log P > 4.5) alongside spectral overlap across 220–230 nm.'),
        ('Their ester linkages can hydrolyze during prolonged shelf storage [7].',
         'Ester linkages remain susceptible to hydrolytic cleavage during prolonged shelf storage [7].'),
        ('For routine quality control, manufacturers require stability-indicating methods that separate both actives from oily matrix excipients and breakdown products in line with ICH Q1A(R2) and Q2(R2) guidelines [8,9].',
         'Industrial quality control demands stability-indicating protocols that separate both pyrethroids from oily matrix components and degradation products per ICH Q1A(R2)/Q2(R2) directives [8,9].'),
        ('Gas chromatography-mass spectrometry (GC-MS) protocols [2] demand extensive electrical power (> 3 kWh per run) and multi-step liquid-liquid extraction using chlorinated solvents or n-hexane.',
         'Gas chromatography-mass spectrometry (GC-MS) [2] requires elevated electrical energy (> 3 kWh/run) and multi-step extraction utilizing chlorinated solvents or n-hexane.'),
        ('High-performance thin-layer chromatography (HPTLC) methods [29] consume hazardous solvents such as toluene and diethyl ether.',
         'Thin-layer chromatography (HPTLC) [29] consumes hazardous toluene and diethyl ether.'),
        ('Standard HPLC monographs [27] rely predominantly on acetonitrile.',
         'Conventional HPLC monographs [27] rely upon toxic acetonitrile.'),
        ('Acetonitrile is a fossil-derived solvent that generates toxic cyanide gas during thermal waste treatment.',
         'Acetonitrile represents a petroleum derivative generating toxic cyanide vapors upon incineration.'),
        ('Under Green Analytical Chemistry (GAC) [10,11] and White Analytical Chemistry (WAC) [12] frameworks, bio-ethanol is an attractive, renewable substitute with minimal toxicity [13–16].',
         'Within Green Analytical Chemistry (GAC) [10,11] and White Analytical Chemistry (WAC) [12] principles, bio-ethanol serves as an attractive renewable alternative [13–16].'),
        ('Ethanol\'s viscosity at room temperature is higher than that of acetonitrile (1.08 vs 0.34 mPa·s at 25 °C), generating greater backpressure.',
         'Higher solvent viscosity (1.08 vs 0.34 mPa·s at 25 °C) increases hydrodynamic backpressure.'),
        ('However, this hydrodynamic challenge can be managed through column selection and sensible flow control.',
         'Nevertheless, appropriate column dimensions and flow settings readily accommodate this pressure profile.'),
        ('Early greenness assessment tools like the Analytical Eco-Scale [23] and original GAPI [24] provide useful broad scores, but they miss key aspects of sample preparation hazard, solvent supply chains, and balance across green principles.',
         'While the Analytical Eco-Scale [23] and original GAPI [24] offer foundational scores, they overlook sample preparation hazards, solvent supply life cycles, and principle balancing.'),
        ('More recent metric systems resolve these limitations: Modified GAPI (MoGAPI) [17], Complex Modified GAPI (ComplexMoGAPI) [18], Analytical Green Star Area (AGSA) [19], Green Environmental Assessment and Rating for Solvents (GEARS) [20], and AGSA for Sample Preparation (AGSA-Prep) [21].',
         'Advanced metric systems resolve these limitations: Modified GAPI (MoGAPI) [17], Complex Modified GAPI (ComplexMoGAPI) [18], Analytical Green Star Area (AGSA) [19], Green Environmental Assessment and Rating for Solvents (GEARS) [20], and AGSA for Sample Preparation (AGSA-Prep) [21].'),
        ('Reference standards of D-tetramethrin (98.2% certified purity) and trans-cyphenothrin (98.5% certified purity) were supplied by Sumitomo Chemical Co., Ltd. (Tokyo, Japan).',
         'Analytical standards of D-tetramethrin (98.2% certified purity) and trans-cyphenothrin (98.5% certified purity) originated from Sumitomo Chemical Co., Ltd. (Tokyo, Japan).'),
        ('Commercial KIROX MD insecticidal aerosol canisters (labeled: 2.7% w/v D-tetramethrin, 0.9% w/v trans-cyphenothrin; Batch NOM4) were manufactured by Misr Detergents (MD Industries) and obtained from local retail stock.',
         'Commercial KIROX MD aerosol canisters (labeled: 2.7% w/v D-tetramethrin, 0.9% w/v trans-cyphenothrin; Batch NOM4, Misr Detergents) were procured from local retail stock.'),
        ('Absolute ethanol (HPLC grade, ≥ 99.8%) and acetone (analytical grade) were purchased from Merck (Darmstadt, Germany).',
         'Absolute ethanol (HPLC grade, ≥ 99.8%) and acetone (analytical grade) were acquired from Merck (Darmstadt, Germany).'),
        ('Hydrochloric acid (37%), sodium hydroxide pellets, and hydrogen peroxide (30%) were sourced from Sigma-Aldrich.',
         'Hydrochloric acid (37%), sodium hydroxide pellets, and hydrogen peroxide (30%) were supplied by Sigma-Aldrich.'),
        ('Ultrapure water (> 18.2 MΩ·cm) came from a Milli-Q water system (Millipore, Bedford, MA, USA).',
         'Ultrapure water (> 18.2 MΩ·cm) was dispensed by a Milli-Q purification unit (Millipore, Bedford, MA, USA).'),
        ('Chromatographic measurements were carried out on an Agilent 1100 series HPLC system (Agilent Technologies, Waldbronn, Germany) configured with a G1311A quaternary pump, G1313A autosampler, G1316A column compartment, and G1315B diode array detector (DAD), driven by ChemStation software.',
         'Chromatographic instrumentation comprised an Agilent 1100 HPLC system (Agilent Technologies, Waldbronn, Germany) equipped with a G1311A quaternary pump, G1313A autosampler, G1316A column compartment, and G1315B diode array detector (DAD), controlled via ChemStation software.'),
        ('The mobile phase was water:ethanol (5:95, v/v), filtered through a 0.45 µm nylon membrane filter and degassed by ultrasonic bath for 15 min.',
         'The binary eluent contained water:ethanol (5:95, v/v), vacuum-filtered through a 0.45 µm nylon membrane and degassed ultrasonically for 15 min.'),
        ('Isocratic elution ran at 1.5 mL/min with the column compartment held at 25 ± 2 °C.',
         'Isocratic elution proceeded at 1.5 mL/min with column temperature maintained at 25 ± 2 °C.'),
        ('The injection volume was 20 µL, Absorbance detection was tracked at 220 nm, and each run took 22.0 min.',
         'Injections of 20 µL were monitored spectrophotometrically at 220 nm across 22.0-min run intervals.'),
        ('Standard Stock Solution: We weighed 225.0 mg D-tetramethrin and 75.0 mg trans-cyphenothrin into a 100-mL volumetric flask, dissolved the material in acetone, sonicated for 10 min, and diluted to mark.',
         'Standard Stock Formulation: Accurately weighed 225.0 mg D-tetramethrin and 75.0 mg trans-cyphenothrin were transferred into a 100-mL volumetric flask, dissolved in acetone, sonicated for 10 min, and diluted to volume.'),
        ('Working Standard Solution: A 5.0-mL portion of stock solution was transferred into a 50-mL volumetric flask and brought to volume with acetone, giving 225.0 µg/mL D-tetramethrin and 75.0 µg/mL trans-cyphenothrin.',
         'Working Standard Preparation: A 5.0-mL aliquot of stock solution was transferred into a 50-mL flask and diluted with acetone, yielding 225.0 µg/mL D-tetramethrin and 75.0 µg/mL trans-cyphenothrin.'),
        ('The mixture was passed through a 0.45 µm PTFE syringe filter before injection.',
         'The resulting mixture was filtered through a 0.45 µm PTFE disc prior to chromatographic injection.'),
        ('Aerosol Canister Sampling: Aerosol cans were stood upright under an active fume hood and gently depressurized without shaking until propellant gas stopped escaping.',
         'Canister Sampling: Aerosol units stood upright inside an exhaust hood and were depressurized gradually without agitation until propellant discharge ceased completely.'),
        ('A 5.0-mL sample of the remaining liquid concentrate was transferred into a 25-mL volumetric flask, dissolved in acetone, sonicated for 10 min, and diluted to volume. Next, 5.0-mL of this solution was diluted to 10-mL with acetone and filtered through a 0.45 µm PTFE disc.',
         'A 5.0-mL portion of remaining liquid concentrate was transferred into a 25-mL volumetric flask, dissolved in acetone, sonicated for 10 min, and brought to mark; subsequent 5.0-to-10 mL dilution with acetone and 0.45 µm PTFE filtration completed sample preparation.'),
        ('Analytical validation adhered to ICH Q2(R2) directives [9], testing system suitability (n = 7), specificity (blank and placebo solutions), linearity (50%–150% range, 5 concentrations in triplicate), accuracy (50%, 100%, and 150% spike levels, n = 9), and precision (repeatability n = 6; intermediate precision across two analysts, two days, and two column lots, evaluated by one-way ANOVA). Forced degradation trials followed ICH Q1A(R2) guidelines [8]: acid stress (1.0 M HCl, 4 h), alkali stress (0.1 M NaOH, 1 h), oxidative stress (3% H2O2, 6 h), dry heat (60 °C, 6 h), and ultraviolet exposure (254 nm, 24 h). Peak purity was checked across all stressed runs with the diode array detector.',
         'Analytical validation adhered to ICH Q2(R2) directives [9], appraising system suitability (n = 7), specificity (blank and placebo solutions), linearity (50%–150% range, 5 concentrations in triplicate), accuracy (50%, 100%, and 150% spikes, n = 9), and precision (repeatability n = 6; intermediate precision across two analysts, days, and column lots via one-way ANOVA). Forced degradation followed ICH Q1A(R2) guidelines [8]: acid (1.0 M HCl, 4 h), alkali (0.1 M NaOH, 1 h), oxidative (3% H2O2, 6 h), thermal (60 °C, 6 h), and photolytic stress (254 nm, 24 h), with DAD peak purity monitoring.'),
        ('Switching from acetonitrile to ethanol required balancing chromatographic retention against solvent viscosity. Initial runs using water:ethanol ratios between 80:20 and 90:10 (v/v) produced excessively broad peaks and pushed trans-cyphenothrin retention past 30 min. Raising the ethanol proportion to 95% (5:95, v/v) improved peak symmetry and pulled both compounds into a practical 22-min window. D-Tetramethrin eluted at 8.63 min and trans-cyphenothrin at 18.60 min, yielding a baseline resolution of 13.52. System backpressure held near 172 bar, well below the equipment\'s 400-bar rating. Measuring absorbance at 220 nm gave strong analyte responses while avoiding ethanol\'s lower UV cutoff threshold (~205–210 nm).',
         'Replacing acetonitrile with ethanol required balancing chromatographic retention against eluent viscosity. Initial trials using water:ethanol ratios (80:20 to 90:10, v/v) yielded broad peaks and delayed trans-cyphenothrin retention beyond 30 min. Raising ethanol content to 95% (5:95, v/v) optimized chromatographic symmetry, resolving both targets inside 22 min (D-tetramethrin: 8.63 min; trans-cyphenothrin: 18.60 min; Rs = 13.52). Hydraulic backpressure stabilized near 172 bar—well within equipment limits (400 bar). Spectrophotometric tracking at 220 nm maximized analyte sensitivity while avoiding ethanol\'s UV cutoff (~205–210 nm).'),
        ('Seven replicate standard injections satisfied all ICH acceptance criteria (Table 1). Retention times showed %RSD values of 0.75% for D-tetramethrin and 0.65% for trans-cyphenothrin. Peak area repeatability gave %RSDs of 1.75% and 2.26%. Plate counts averaged above 5,600 and 5,900, while tailing factors remained below 1.30. Specificity tests (Figure 2) showed no interfering signals from the solvent blank or placebo mixture in the elution windows of either active ingredient. Diode array spectral purity plots confirmed that both analyte peaks were spectrally homogeneous, with purity angles falling well within their purity thresholds.',
         'Seven replicate standard injections met ICH acceptance criteria (Table 1). Retention time precision (%RSD) reached 0.75% (D-tetramethrin) and 0.65% (trans-cyphenothrin), with peak area %RSDs of 1.75% and 2.26%. Theoretical plate counts exceeded 5,600 and 5,900, while peak tailing remained below 1.30. Specificity testing (Figure 2) revealed no interfering peaks from blank diluent or placebo matrix within analyte windows, with DAD purity angles confirming spectral homogeneity.'),
        ('Five-point calibration curves showed good linearity from 50% to 150% of target concentrations (Table 2, Figure 1). Least-squares regression produced y = 52,258.49 x - 576,219.33 (R² = 0.9911) for D-tetramethrin (112.5–337.5 µg/mL) and y = 44,443.04 x + 118,031.51 (R² = 0.9992) for trans-cyphenothrin (37.5–112.5 µg/mL). Residual analysis confirmed homoscedastic variance across the tested concentration span. Detection limits (LOD) were 42.84 µg/mL for D-tetramethrin and 4.23 µg/mL for trans-cyphenothrin, with quantitation limits (LOQ) of 129.82 µg/mL and 12.82 µg/mL.',
         'Five-point calibration plots exhibited linear responses spanning 50%–150% of target levels (Table 2, Figure 1). Least-squares regression yielded y = 52,258.49 x - 576,219.33 (R² = 0.9911) for D-tetramethrin (112.5–337.5 µg/mL) and y = 44,443.04 x + 118,031.51 (R² = 0.9992) for trans-cyphenothrin (37.5–112.5 µg/mL). Residual analysis confirmed homoscedastic error distributions. Detection limits (LOD) were 42.84 µg/mL (D-tetramethrin) and 4.23 µg/mL (trans-cyphenothrin), with corresponding quantitation limits (LOQ) of 129.82 µg/mL and 12.82 µg/mL.'),
        ('Accuracy verification entailed spiking inactive matrix at 50%, 100%, and 150% of nominal levels (Table 3). Across nine determinations, mean recoveries were 99.02% (%RSD = 0.94%) for D-tetramethrin and 100.46% (%RSD = 0.44%) for trans-cyphenothrin, well within standard regulatory bounds (98.0%–102.0%). Precision evaluation (Table 4) yielded repeatability RSDs of 0.39% (D-tetramethrin) and 0.24% (trans-cyphenothrin). Intermediate precision across different operators, days, and column serial numbers yielded RSDs below 0.60%. One-way ANOVA tests showed no significant difference between test days (F = 0.698, p = 0.423 for D-tetramethrin; F = 0.812, p = 0.388 for trans-cyphenothrin), demonstrating method ruggedness.',
         'Accuracy trials spiking placebo matrix across 50%, 100%, and 150% levels (n = 9, Table 3) demonstrated mean analytical recoveries of 99.02% (%RSD = 0.94%) for D-tetramethrin and 100.46% (%RSD = 0.44%) for trans-cyphenothrin, satisfying regulatory limits (98.0%–102.0%). Precision assessments (Table 4) gave repeatability RSDs of 0.39% (D-tetramethrin) and 0.24% (trans-cyphenothrin). Intermediate ruggedness across operators, days, and column batches retained RSDs below 0.60%, with one-way ANOVA indicating no significant inter-day variation (F = 0.698, p = 0.423 for D-tetramethrin; F = 0.812, p = 0.388 for trans-cyphenothrin).'),
        ('Forced degradation experiments confirmed that intact active ingredients separate cleanly from decomposition products under all stress conditions (Table 5, Figure 3). Acid treatment (1.0 M HCl) degraded 13.80% of D-tetramethrin (Rs = 7.85) and 27.57% of trans-cyphenothrin (Rs = 1.47). Alkaline exposure (0.1 M NaOH) caused 6.14% and 8.31% loss (Rs = 3.50 and 1.40). Peroxide oxidation (3% H2O2) broke down 28.49% of trans-cyphenothrin (Rs = 1.50) and 8.70% of D-tetramethrin (Rs = 3.52). Thermal stress at 60 °C caused 22.39% loss of trans-cyphenothrin (Rs = 1.28) and 3.50% of D-tetramethrin (Rs = 2.39). Both actives proved photostable under UV light, with less than 3% degradation. In every instance, diode array peak purity verified that no breakdown products co-eluted with parent compounds, confirming the stability-indicating capability of the assay.',
         'Forced degradation experiments confirmed baseline separation between intact pyrethroids and breakdown products across all stress conditions (Table 5, Figure 3). Acidic exposure (1.0 M HCl) degraded 13.80% D-tetramethrin (Rs = 7.85) and 27.57% trans-cyphenothrin (Rs = 1.47). Alkaline hydrolysis (0.1 M NaOH) induced 6.14% and 8.31% decomposition (Rs = 3.50 and 1.40). Peroxide oxidation (3% H2O2) degraded 28.49% trans-cyphenothrin (Rs = 1.50) and 8.70% D-tetramethrin (Rs = 3.52). Thermal stress (60 °C) triggered 22.39% loss in trans-cyphenothrin (Rs = 1.28) and 3.50% in D-tetramethrin (Rs = 2.39). UV irradiation revealed robust photostability (< 3% loss). Throughout all challenges, DAD spectral purity verified absence of co-eluting degradants.'),
        ('To evaluate the assay beyond ecological impact alone, we applied White Analytical Chemistry (WAC / RGB12 model), the Blue Applicability Grade Index (BAGI), the Analytical Eco-Scale (AES), and direct carbon footprint estimation (Figure 5). Total WAC whiteness reached 83.33%, combining strong analytical validation (Red: 88.5%), environmental responsibility (Green: 82.5%), and economic feasibility (Blue: 79.0%). BAGI scored 80.0 / 100, credited to simple dilute-and-shoot sample preparation, room temperature operation, and an ordinary C18 column. The Analytical Eco-Scale earned an 88/100 rating with only 12 penalty points deducted. Direct carbon footprint calculations indicated 0.00145 kg CO2 eq/sample—a twelve-fold reduction compared to literature GC-MS methods (0.01850 kg CO2 eq/sample).',
         'Holistic sustainability profiling beyond greenness integrated White Analytical Chemistry (WAC / RGB12), the Blue Applicability Grade Index (BAGI), Analytical Eco-Scale (AES), and carbon footprint estimation (Figure 5). Overall WAC whiteness reached 83.33% (Red: 88.5%, Green: 82.5%, Blue: 79.0%). BAGI scored 80.0/100, reflecting dilute-and-shoot execution, ambient column operation, and standard C18 hardware. Analytical Eco-Scale evaluation afforded 88/100 (12 penalty points). Direct carbon emissions totaled 0.00145 kg CO2 eq/sample—a twelve-fold reduction relative to published GC-MS workflows (0.01850 kg CO2 eq/sample).'),
        ('Commercial KIROX MD aerosol units were assayed to test real-world applicability. Six independent containers demonstrated average recovery figures of 100.2 ± 0.4% for D-tetramethrin and 100.5 ± 0.3% for trans-cyphenothrin, meeting commercial release specifications (90.0%–110.0%). No interference from container propellant or aerosol propellants was observed, confirming the assay\'s fitness for routine batch testing.',
         'Real-world applicability was verified by assaying commercial KIROX MD aerosol canisters. Six independent containers demonstrated mean recoveries of 100.2 ± 0.4% (D-tetramethrin) and 100.5 ± 0.3% (trans-cyphenothrin), satisfying commercial release specifications (90.0%–110.0%). Excipient propellants exhibited zero chromatographic interference, verifying fitness for routine batch release.'),
        ('We developed and validated an isocratic RP-HPLC method for analyzing D-tetramethrin and trans-cyphenothrin in commercial pressurized aerosols. Switching from acetonitrile to bio-ethanol eliminated toxic cyanide waste streams while maintaining complete chromatographic separation (Rs = 13.52). The method complied with all ICH Q2(R2) requirements and cleanly separated breakdown products across five forced degradation conditions. Comparative evaluation across ten greenness, whiteness, and blueness metrics confirmed clear ecological and practical benefits over existing GC-MS, HPTLC, and conventional HPLC protocols, offering an efficient, low-waste procedure for routine industrial release.',
         'This study developed and qualified an isocratic RP-HPLC assay for quantifying D-tetramethrin and trans-cyphenothrin within commercial aerosols. Replacing acetonitrile with bio-ethanol eliminated toxic cyanide waste streams whilst maintaining baseline chromatographic resolution (Rs = 13.52). Analytical validation complied with ICH Q2(R2) criteria, cleanly separating degradants across five stress challenges. Comprehensive benchmarking across ten sustainability, whiteness, and blueness frameworks verified ecological superiority over legacy GC-MS, HPTLC, and conventional HPLC methods, providing an efficient, low-waste procedure for industrial quality assurance.')
    ]
    
    for old, new in replacements:
        t = t.replace(old, new)
        
    return t

def humanize_2nd(text):
    t = text
    
    # Clean section numbers or bullet points
    t = re.sub(r'^\d+\.\s+', '', t, flags=re.MULTILINE)
    t = re.sub(r'^\d+\.\d+\.\s+', '', t, flags=re.MULTILINE)
    t = re.sub(r'^[•\-\*]\s+', '', t, flags=re.MULTILINE)
    
    # AI tells and repetitive patterns
    t = t.replace('Here, we describe an isocratic RP-HPLC method utilizing an 80% aqueous buffer with 10% bio-ethanol and 10% methanol.',
                  'This investigation introduces an isocratic RP-HPLC method utilizing an 80% aqueous buffer with 10% bio-ethanol and 10% methanol.')
    t = t.replace('Here, we present', 'We report')
    t = t.replace('comprehensive assessment', 'multidimensional evaluation')
    t = t.replace('met all acceptance criteria', 'complied with standard validation thresholds')
    t = t.replace('met all pre-established criteria', 'fulfilled all ICH specifications')
    t = t.replace('A green, stability-indicating reversed-phase HPLC method was developed and validated for the simultaneous determination of ciprofloxacin hydrochloride and tinidazole in commercial tablets (Floxotinazole FCT). Acetonitrile was eliminated, using an 80% aqueous mobile phase: methanol:ethanol:Solution C (0.025 M orthophosphoric acid, pH 3.0 adjusted with triethanolamine) (10:10:80 v/v/v) on a C18 column (250 × 4.6 mm, 5 µm) at 1.5 mL/min with UV detection at 315 nm.',
                  'An isocratic green RP-HPLC method quantifies ciprofloxacin hydrochloride and tinidazole simultaneously in commercial tablets (Floxotinazole FCT). Toxic acetonitrile was eliminated using an 80% aqueous eluent comprising methanol, ethanol, and Solution C (0.025 M orthophosphoric acid, pH 3.0 adjusted with triethanolamine; 10:10:80, v/v/v) pumped at 1.5 mL/min across a C18 column (250 × 4.6 mm, 5 µm) under 315 nm UV detection.')
    t = t.replace('The method provides an eco-friendly protocol for routine industrial batch release and stability monitoring.',
                  'This eco-friendly protocol offers robust capability for routine industrial batch release and stability testing.')
    
    replacements = [
        ('Combining the broad-spectrum fluoroquinolone ciprofloxacin hydrochloride with the antiprotozoal and antibacterial nitroimidazole tinidazole provides synergistic clinical efficacy against mixed aerobic-anaerobic infections, including intra-abdominal, pelvic, and severe gastrointestinal disorders [1,2].',
         'Co-administering the fluoroquinolone ciprofloxacin hydrochloride with the nitroimidazole tinidazole provides synergistic clinical efficacy against mixed aerobic-anaerobic infections, including intra-abdominal, pelvic, and severe gastrointestinal disorders [1,2].'),
        ('Due to their complementary pharmacokinetics and broad antimicrobial spectrum, fixed-dose combination tablets (e.g., Floxotinazole FCT, containing 500 mg ciprofloxacin and 600 mg tinidazole) are widely prescribed worldwide.',
         'Given their complementary pharmacokinetics and antimicrobial coverage, fixed-dose combination tablets (e.g., Floxotinazole FCT, containing 500 mg ciprofloxacin and 600 mg tinidazole) are widely prescribed globally.'),
        ('Regulatory authorities mandate validated, stability-indicating assays for commercial solid dosage forms to monitor active ingredients in the presence of excipients and degradation products [3-5].',
         'Regulatory pharmacopeias mandate validated, stability-indicating assays for commercial solid dosage forms to monitor active drugs alongside excipients and degradation products [3-5].'),
        ('However, published chromatographic monographs and literature methods for this binary combination rely heavily on acetonitrile-phosphate mixtures (20%–40% v/v) or steep gradient profiles [6-10].',
         'Nevertheless, reported chromatographic monographs for this binary formulation rely heavily on acetonitrile-phosphate mixtures (20%–40% v/v) or complex gradient programs [6-10].'),
        ('Acetonitrile is a volatile petrochemical solvent classified as an environmental pollutant that produces toxic hydrogen cyanide during thermal waste treatment [11,12].',
         'Acetonitrile represents a volatile petrochemical derivative that releases hazardous hydrogen cyanide upon incineration [11,12].'),
        ('Planar chromatography (HPTLC) techniques reported for these drugs frequently employ toxic chlorinated or aromatic solvents (chloroform, toluene) with liquid-liquid extraction [9].',
         'Planar chromatographic (HPTLC) procedures frequently employ toxic chlorinated or aromatic solvents (chloroform, toluene) coupled with liquid-liquid extraction [9].'),
        ('In accordance with Green Analytical Chemistry (GAC) [13] and White Analytical Chemistry (WAC) [14] frameworks, replacing hazardous modifiers with water-rich mobile phases and bio-renewable alcohols reduces worker exposure and waste disposal hazards [15].',
         'Under Green Analytical Chemistry (GAC) [13] and White Analytical Chemistry (WAC) [14] principles, substituting hazardous modifiers with aqueous-rich eluents and renewable alcohols reduces occupational exposure and waste hazards [15].'),
        ('Working reference standards of ciprofloxacin hydrochloride (98.86% purity) and tinidazole (98.60% purity) came with manufacturer certificates of analysis.',
         'Analytical standards of ciprofloxacin hydrochloride (98.86% purity) and tinidazole (98.60% purity) were obtained with certified assay credentials.'),
        ('Commercial Floxotinazole FCT tablets (labeled: 500 mg ciprofloxacin, equivalent to 582.2 mg ciprofloxacin HCl, and 600 mg tinidazole; average tablet weight: 1400 mg) were purchased from a local pharmacy.',
         'Commercial Floxotinazole FCT tablets (labeled: 500 mg ciprofloxacin, equivalent to 582.2 mg ciprofloxacin HCl, and 600 mg tinidazole; average tablet weight: 1400 mg) were procured from local pharmacy stock.'),
        ('HPLC-grade methanol and absolute ethanol were from Merck (Darmstadt, Germany).',
         'HPLC-grade methanol and absolute ethanol originated from Merck (Darmstadt, Germany).'),
        ('Analytical-grade orthophosphoric acid (85%), triethanolamine (TEA), hydrochloric acid (37%), sodium hydroxide, and 30% hydrogen peroxide were from Sigma-Aldrich.',
         'Orthophosphoric acid (85%), triethanolamine (TEA), hydrochloric acid (37%), sodium hydroxide, and 30% hydrogen peroxide were sourced from Sigma-Aldrich.'),
        ('Deionized water (> 18.2 MΩ·cm) was purified through a Milli-Q system (Millipore, Bedford, MA, USA).',
         'Deionized water (> 18.2 MΩ·cm) was prepared using a Milli-Q filtration system (Millipore, Bedford, MA, USA).'),
        ('The column was a standard C18 (250 × 4.6 mm, 5 µm, USP L1).',
         'Chromatographic separation employed a standard C18 stationary phase (250 × 4.6 mm, 5 µm, USP L1).'),
        ('Flow rate was 1.5 mL/min at 30°C, injection volume was 10 µL, and detection was monitored at 315 nm. Operating pressure remained steady at ~145 bar.',
         'Flow rate was maintained at 1.5 mL/min at 30°C, with 10-µL injections and spectrophotometric detection at 315 nm; column backpressure stabilized at ~145 bar.'),
        ('Standard Stock Solution: We weighed 23.3 mg of ciprofloxacin HCl and 24.0 mg of tinidazole into a 10-mL volumetric flask, dissolved the powder in mobile phase, and sonicated for 1 min. A 5.0-mL portion was transferred to a 50-mL volumetric flask and diluted to volume, giving working concentrations of 0.233 mg/mL (232.88 µg/mL) ciprofloxacin HCl and 0.240 mg/mL (240.0 µg/mL) tinidazole. The solution was filtered through a 0.45 µm PTFE syringe filter before injection.',
         'Stock Standard Preparation: Accurately weighed 23.3 mg ciprofloxacin HCl and 24.0 mg tinidazole were dissolved in mobile phase inside a 10-mL volumetric flask and sonicated for 1 min; transferring a 5.0-mL aliquot into a 50-mL flask and diluting to volume yielded 0.233 mg/mL (232.88 µg/mL) ciprofloxacin HCl and 0.240 mg/mL (240.0 µg/mL) tinidazole. Injections followed 0.45 µm PTFE membrane filtration.'),
        ('Tablet Sample Preparation (Dilute-and-Shoot): Ten Floxotinazole FCT tablets were weighed to determine average tablet weight (1400 mg) and ground to fine powder in an agate mortar. An accurately weighed quantity of powder (560.0 mg, containing ~232.88 mg ciprofloxacin HCl and 240.0 mg tinidazole) was transferred to a 100-mL volumetric flask. We added ~60 mL of mobile phase, shook mechanically for 2 min, and sonicated for 3 min. After bringing to volume with mobile phase, a 5.0-mL aliquot was diluted to 50 mL with mobile phase and passed through a 0.45 µm PTFE filter.',
         'Tablet Assay Preparation: Ten Floxotinazole FCT tablets were weighed to determine mean tablet mass (1400 mg) and pulverized using an agate mortar. Accurately weighed powder (560.0 mg, equivalent to ~232.88 mg ciprofloxacin HCl and 240.0 mg tinidazole) was transferred into a 100-mL flask, dispersed in ~60 mL mobile phase, mechanically agitated for 2 min, and sonicated for 3 min. Following dilution to volume, a 5.0-mL aliquot was diluted to 50 mL with mobile phase and filtered through a 0.45 µm PTFE disc.'),
        ('Our goal was to cut organic solvent use while preserving peak shape. Running at pH 3.0 suppressed silanol ionization on the silica surface and kept ciprofloxacin protonated. Adding triethanolamine as a base competitor masked residual silanols, which eliminated peak tailing. The ternary combination of methanol:ethanol:Solution C (10:10:80 v/v/v) gave sharp, symmetrical peaks for both compounds. Even with ethanol in the mix, the high water fraction (80%) kept column backpressure at ~145 bar. Tinidazole eluted at 10.92 min and ciprofloxacin at 14.48 min, giving a baseline resolution of 5.72 within an 18-min run.',
         'Method optimization sought to minimize organic consumption while preserving chromatographic resolution. Buffering at pH 3.0 suppressed silanol ionization and maintained ciprofloxacin protonation, while triethanolamine acted as a sacrificial base competitor to eliminate peak tailing. The ternary mobile phase (methanol:ethanol:Solution C, 10:10:80 v/v/v) yielded sharp symmetrical peaks for both analytes, maintaining hydraulic backpressure at ~145 bar due to the high aqueous content (80%). Tinidazole eluted at 10.92 min and ciprofloxacin at 14.48 min, achieving baseline resolution (Rs = 5.72) within an 18-min run window.'),
        ('Six consecutive standard injections satisfied USP and ICH criteria (Table 1). Retention times were reproducible, with %RSD of 0.35% for both analytes. Plate counts reached 7,882 for tinidazole and 6,216 for ciprofloxacin, with USP tailing factors of 1.06 and 1.22. Area repeatability %RSD was 0.35%.',
         'Six consecutive standard injections satisfied USP and ICH specifications (Table 1). Retention precision gave %RSD of 0.35% for both analytes, while peak area repeatability reached 0.35% %RSD. Column efficiency reached 7,882 theoretical plates (tinidazole) and 6,216 plates (ciprofloxacin), with USP tailing factors of 1.06 and 1.22.'),
        ('Figure 2 illustrates representative profiles for diluent blank, placebo excipients, working standard, and tablet extract. The placebo showed no peaks in the retention windows of either drug. Diode array spectral purity checks showed uniform absorbance profiles across each peak.',
         'Figure 2 depicts chromatograms of diluent blank, placebo excipients, working standard, and tablet extract. Placebo excipients showed zero peaks within drug retention windows, while DAD spectral purity profiling verified uniform absorbance across each peak.'),
        ('Calibration curves were constructed across five levels spanning 50% to 150% of the working concentrations (Table 2, Figure 1). Regression equations were y = 7,723.6x + 1,240.0 (R² = 0.99997) for ciprofloxacin (116.4–349.2 µg/mL) and y = 8,627.9x + 1,850.0 (R² = 0.99997) for tinidazole (120.0–360.0 µg/mL). Residual plots showed random scatter across zero. Limits of detection were 0.0125 µg (1.25 µg/mL) for ciprofloxacin and 0.0105 µg (1.05 µg/mL) for tinidazole; limits of quantitation were 0.0380 µg (3.80 µg/mL) and 0.0317 µg (3.17 µg/mL).',
         'Five-point calibration plots spanned 50%–150% of target working concentrations (Table 2, Figure 1). Least-squares regression yielded y = 7,723.6x + 1,240.0 (R² = 0.99997) for ciprofloxacin (116.4–349.2 µg/mL) and y = 8,627.9x + 1,850.0 (R² = 0.99997) for tinidazole (120.0–360.0 µg/mL), with homoscedastic residual distributions. Detection limits (LOD) were 0.0125 µg (1.25 µg/mL) for ciprofloxacin and 0.0105 µg (1.05 µg/mL) for tinidazole, with quantitation limits (LOQ) of 0.0380 µg (3.80 µg/mL) and 0.0317 µg (3.17 µg/mL).'),
        ('Recovery was evaluated at 50%, 100%, and 150% spike levels in triplicate (n = 9, Table 3). Mean recovery was 100.90% (%RSD = 0.29%) for ciprofloxacin and 100.19% (%RSD = 0.24%) for tinidazole, within the 98.0%–102.0% acceptance window.',
         'Spiking inactive excipient blends across 50%, 100%, and 150% levels (n = 9, Table 3) demonstrated mean analytical recoveries of 100.90% (%RSD = 0.29%) for ciprofloxacin and 100.19% (%RSD = 0.24%) for tinidazole, satisfying standard regulatory limits (98.0%–102.0%).'),
        ('Six independent tablet preparations yielded mean assay values of 100.94% (%RSD = 0.60%) for ciprofloxacin and 100.12% (%RSD = 0.60%) for tinidazole (Table 4). Intermediate precision tested across two analysts on different days showed %RSD values below 0.53%, confirming method ruggedness.',
         'Assaying six commercial tablet preparations yielded mean contents of 100.94% (%RSD = 0.60%) for ciprofloxacin and 100.12% (%RSD = 0.60%) for tinidazole (Table 4); inter-analyst intermediate precision across separate operating sessions retained %RSD below 0.53%.'),
        ('Stress studies exposed tablet formulations to five degradation conditions (Table 5, Figure 3). Both drugs resisted acid, thermal, and photolytic stress (loss < 5%). Alkaline conditions (0.1 M NaOH at 60°C) produced moderate loss (< 8%). In contrast, 30% H2O2 provoked 43.8% degradation, generating a major degradation product at 6.20 min. This degradant peak resolved cleanly from tinidazole (Rs = 4.72) and ciprofloxacin (Rs > 8.0). PDA peak purity angles remained below purity thresholds throughout, proving the assay is stability-indicating.',
         'Forced degradation trials subjected tablet formulations to five stress environments (Table 5, Figure 3). Both actives resisted acidic, thermal, and photolytic degradation (loss < 5%), while alkaline digestion (0.1 M NaOH at 60°C) induced moderate loss (< 8%). In contrast, 30% H2O2 provoked 43.8% degradation, forming a prominent breakdown product at 6.20 min that resolved cleanly from tinidazole (Rs = 4.72) and ciprofloxacin (Rs > 8.0). DAD spectral purity angles remained strictly below purity thresholds throughout, establishing stability-indicating capability.'),
        ('The 80% aqueous mobile phase raised the GEARS total solvent score to 92.13%, compared to 78.63% for conventional ACN methods and 31.40% for HPTLC. MoGAPI and ComplexMoGAPI scores reached 70.0 and 72.5, driven by minimal sample preparation and safe waste streams. AGSA and AGSA-Prep star areas were 42.15% and 58.40%, showing balanced coverage across the 12 GAC principles. AGREE scored 0.81.',
         'Formulating an 80% aqueous eluent elevated the GEARS solvent score to 92.13%, outperforming conventional acetonitrile methods (78.63%) and planar HPTLC (31.40%). MoGAPI and ComplexMoGAPI ratings reached 70.00 and 72.50, driven by direct sample preparation and environmentally benign waste streams. AGSA and AGSA-Prep polygonal star areas attained 42.15% and 58.40%, while the AGREE greenness metric scored 0.81.'),
        ('Under White Analytical Chemistry (WAC / RGB12), total whiteness reached 87.17% (Red: 91.0%, Green: 88.0%, Blue: 82.5%). BAGI blueness was 85.0 / 100, reflecting routine C18 availability and dilute-and-shoot simplicity. Deducting 9 penalty points gave an Analytical Eco-Scale score of 91 / 100. Direct carbon emissions were 0.00112 kg CO2 eq/sample, seven times lower than conventional HPLC (0.00820 kg CO2 eq).',
         'Evaluation via White Analytical Chemistry (WAC / RGB12) registered 87.17% total whiteness (Red: 91.0%, Green: 88.0%, Blue: 82.5%), whereas the BAGI blueness index scored 85.0/100, driven by direct C18 compatibility and dilute-and-shoot execution. Deducting 9 penalty points afforded an Analytical Eco-Scale rating of 91/100, and carbon emission profiling indicated 0.00112 kg CO2 eq/sample—seven-fold below conventional HPLC (0.00820 kg CO2 eq).'),
        ('An isocratic RP-HPLC assay was developed and validated for the simultaneous determination of ciprofloxacin hydrochloride and tinidazole in commercial tablets. Using an 80% aqueous buffer with 10% ethanol and 10% methanol eliminated acetonitrile while maintaining baseline separation (Rs = 5.72). The method fulfilled ICH Q2(R2) and USP 36-NF31 criteria and resolved all degradation products under five stress conditions. Assessment across ten sustainability, whiteness, and applicability metrics showed lower solvent hazards, reduced waste, and operational simplicity relative to reported monographs, making the procedure suitable for routine batch release and stability testing.',
         'This study established and validated an isocratic RP-HPLC assay for quantifying ciprofloxacin hydrochloride and tinidazole in commercial tablets. Formulating an 80% aqueous eluent with 10% bio-ethanol and 10% methanol omitted acetonitrile whilst maintaining baseline chromatographic resolution (Rs = 5.72). Validation fulfilled ICH Q2(R2) and USP 36-NF31 specifications, cleanly separating degradants across five stress challenges. Comprehensive evaluation across ten sustainability, whiteness, and blueness metrics verified lower solvent hazards, reduced waste, and superior operational simplicity over reported monographs, confirming suitability for routine release and stability monitoring.')
    ]
    
    for old, new in replacements:
        t = t.replace(old, new)
        
    return t

with open('1st_enriched.txt', 'r', encoding='utf-8') as f:
    text1 = f.read()

with open('2nd_enriched.txt', 'r', encoding='utf-8') as f:
    text2 = f.read()

h1 = humanize_1st(text1)
h2 = humanize_2nd(text2)

with open('1st_humanized_v2.txt', 'w', encoding='utf-8') as f:
    f.write(h1)

with open('2nd_humanized_v2.txt', 'w', encoding='utf-8') as f:
    f.write(h2)

print('Generated 1st_humanized_v2.txt and 2nd_humanized_v2.txt')
